### ISSUE TITLE
"Not enough credits" Error page when trying to join workshops

### ISSUE THREAD

**Issue by KonnorThatcher** [breatheco-de/breatheco-de#7558]
### Bug description

![Opera Snapshot_2024-06-30_235114_breathecode-test herokuapp com](https://github.com/breatheco-de/breatheco-de/assets/131403452/f9e80a0a-4fd2-440a-bf52-68a465b15a60)

Every time I try to join events I should have access to, I get the “You don’t have enough credits to access this service: event_join” error screen, even though I have consumables and those consumables are of the correct event type.

Here are some of the events I tried to join:
https://breathecode-test.herokuapp.com/admin/events/event/822/
https://breathecode-test.herokuapp.com/admin/events/event/821/
https://breathecode-test.herokuapp.com/admin/events/event/818/

### Steps to reproduce

I created an account with a paid plan, and then I made sure one of the above events linked were currently live and made sure it was part of my event type set. Then I simply tried to join the event.

### Expected behavior

It should redirect me to the url of the event where it's being streamed.

**Comment by AltaciosTheDev** [comment]
Confirmed.

**Comment by jefer94** [comment]
# Sumary
This issue is related to the latest changes to the decorator, now called `consume`, it matches the slug provided with the `Service.slug` instead of `Service.groups.permissions.codename`.

The workshops consume `join_mentorship` and the mentorings consume `event_join`, none of these were provided to the user, so, the user can't access them.

## Solutions

1. Rename all the services.
2. Create an enum in the services to select the type of services based in the value provided to the decorator `consume`.

## Information

### User
- Email `jdefreitaspinto+testing@gmail.com`.
- The user got `basic` and `free-trial-full-stack-development` free trial.

### Plans

- The user from `basic` got  `geekpal-mentorship-session` 3 units, and `auto-graded-interactive-tutorials`, `join-the-4geeks-community`, and `join-workshops` unlimited units.
- The user from `free-trial-full-stack-development` didn't get any consumables.

### Services related to the consumables

- `geekpal-mentorship-session` has the `Mentorship` group.
- `auto-graded-interactive-tutorials` has the `Legacy` group.
- `join-the-4geeks-community` has `Default` and `Read Only` groups.

### Groups 

- `Default` has `Create my profile`, `Get my profile`, and `Update my profile`.
- `Legacy` has `Join event`, `Get my certificate`, `Get my mentoring sessions`, `Join mentorship`, and `Join live class`.
- `Mentorships` has `Get my mentoring sessions`, and `Join mentorship`.
-  `Read Only` has so many permissions, so, I won't mention each one.

**Comment by tommygonzaleza** [comment]
We should take approach 2

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/1419

**Comment by jefer94** [comment]
Ese test se hizo sin hacer deploy, hay que fijar ahora los campos consumers https://breathecode-test.herokuapp.com/admin/payments/service/75/change/

**Comment by jefer94** [comment]
Ya veo, le cambiastes los nombres a los consumibles a ver, pero bueno, este cambio tambien se hizo
