### ISSUE TITLE
Use rigobot chat in the bootcamps landing

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7821]
The chat should be opened when you click any of the buttons shown in the image. By default, the chat will be shown in the bottom right corner.

First, we should update the context to tell rigo on the page we currently are on and the information about the BootCamp, with the following code:

```js
rigo.updateContext({
  override: true,
  payload: "",
})
```

> In the payload you can send the description of the course and the course modules parsed into text

```js
rigo.show({
     showBubble: true,
     welcomeMessage: `Is there anything you want to know about the ${program} program?`,
     collapsed: false,
     purposeSlug: "4geekscom-public-agent"
})
```

![Screenshot 2024-09-24 at 12 05 43 PM](https://github.com/user-attachments/assets/fc6d5e84-2c4e-4e56-95db-497eb7316c00)

**Comment by gustavomm19** [comment]
When I use the Rigobot target property, the bubble does not show where it should and the chat window has an excessive height.

https://github.com/user-attachments/assets/0386bd93-72e0-44a2-b138-15018c586c95

**Comment by KonnorThatcher** [comment]
The chat bubble and the button to open/close it always appears next to the "Try Rigobot for free" button instead of the bottom right corner of the screen.
![Image](https://github.com/user-attachments/assets/458f31b4-bd88-4707-850b-05ddf78410cf)

Here's how it looks on the Rigobot landing page for reference:
![Image](https://github.com/user-attachments/assets/93e44ba3-3bca-4ecc-9089-9a04ebbc6fae)

**Comment by tommygonzaleza** [comment]
The changes that Konnor added should be discussed with Alejandro and Charly, I agree with him it's weird how it shows in the middle of the screen
